### ISSUE TITLE
Angle icon blocking target / camera icon when target / camera on same point

### ISSUE THREAD

**Issue by mmmenno** [nypl-spacetime/Leaflet.GeotagPhoto#14]
When camera and target are on top of each other, it's very hard to move them apart, because the angle icon is on top of them both. Since I often start tasks with camera and target on the exact same point, this makes it quite hard to do anything at all.

Maybe an adjusted z-index would help?

**Comment by bertspaan** [comment]
Thanks! The camera should be on top, then the angle, then the target. I'll publish a new version right now.
