### ISSUE TITLE
Default icons does not work over CDN

### ISSUE THREAD

**Issue by Abbe98** [nypl-spacetime/Leaflet.GeotagPhoto#15]
The default icon URLs remains(relative URLs) and it results in images being expected on the current domain such as https://example.com/images/crosshair-icon.svg.

The CDN version should have absolute URLs as defaults for icons and other resources.

**Comment by bertspaan** [comment]
Hey @Abbe98, I'm the author of this Leaflet plugin, but I no longer work for the NYPL and I no longer have write access to this repository. And nobody else at NYPL is maintaining this repo, I'm afraid.

If you would make a PR, I can reach out to my former colleagues and see if one of them can accept it.

**Comment by bertspaan** [comment]
Yes, we could move it to a new home (my own GitHub account, or somewhere else). Three things need to happen:

1. I need to tag this repo as archived and put a link to the new one;
2. NPM needs to be updated;
3 We need to notify the Leaflet community and update the link on their plugins page.

What do you think would be a good, new home? Shall I just fork it? I can make you a collaborator on that repo if you want?

**Comment by bertspaan** [comment]
Apparently, I already forked the repo a year ago: https://github.com/bertspaan/Leaflet.GeotagPhoto.

What about using that one? I will reach out to my former NYPL colleagues for steps 1 and 2.
