### ISSUE TITLE
Help needed: How can i use this in angular typescript projects

### ISSUE THREAD

**Issue by MaddyMastering** [nypl-spacetime/Leaflet.GeotagPhoto#18]
I really need to use this library in angular project any help would be appreciated. 

tried using `declare var L: any;` but other leaflet libraries fail when doing this.

it gives error with this configuration 
        var points = {
            type: 'Feature',
            properties: {
                angle: 20
            },
            geometry: {
                type: 'GeometryCollection',
                geometries: [
                    {
                        type: 'Point',
                        coordinates: [
                            6.831243038177491,
                            52.43470397483283
                        ]
                    },
                    {
                        type: 'LineString',
                        coordinates: [
                            [
                                6.831243038177491,
                                52.43470397483283
                            ],
                            [
                                6.831243038177491,
                                52.43470397483283
                            ]
                        ]
                    }
                ]
            }
        };

![image](https://user-images.githubusercontent.com/18150094/88024448-56110680-cb50-11ea-87dc-ac4abcd18842.png)

**Comment by bertspaan** [comment]
It seems you're using an incorrect GeoJSON object to initialize Leaflet.GeotagPhoto.

The following input GeoJSON objects are accepted: https://github.com/nypl-spacetime/field-of-view#api.

Does this work (I can't test it quickly myself right now):

```js
var points = {
  type: 'Feature',
  properties: {
    angle: 20
  },
  geometry: {
    type: 'LineString',
    coordinates: [
      [6.831243, 52.434703],
      [6.831253, 52.434713]
    ]
  }
}
```
